### ISSUE TITLE
Better hex logo

### ISSUE THREAD

**Issue by jl5000** [jl5000/barRacer#1]
If anyone wants to design a more professional looking hex logo, please do.

**Comment by Pilipino** [comment]
Hello Sir @jl5000. I have designed the following hex logo. I hope this is good. Thank you very much! :)

![Artboard 13x](https://user-images.githubusercontent.com/12228528/70487108-37b14a00-1b2f-11ea-9801-6f628935993e.png)

**Comment by jl5000** [comment]
Thanks so much for taking the time to design these! 

I have a couple of minor issues about colour: 1) Would it be possible to go with a colour scheme that could retain the black and white finish line? 2) I feel like the current colour schemes needs more contrast, including making the lines more defined.

I'd definitely be interested to see some more variations, as you've done such a good job.

**Comment by Pilipino** [comment]
![Artboard 15x](https://user-images.githubusercontent.com/12228528/70604979-97dde400-1c34-11ea-89ab-2382e7d9beaa.png)

**Comment by temery275** [comment]
Hi Jamie,
I've had a go too, what do you think of this?

![barRacer_hex](https://user-images.githubusercontent.com/58784826/70643310-a62dff00-1c38-11ea-87f6-4e2839900ac6.png)

Taken quite a minimalistic approach, using greyscale themes and made it look a bit like the RStudio hex stickers!

**Comment by jl5000** [comment]
Thanks both! I think I'm going to have to go with the one by @temery275. I particularly like the shadowing and its sleek look.
